# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='player_one', max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
